#!/usr/bin/python3

import sys

def factorize(n):
    factors = []
    for i in range(2, int(n**(1/2))+1):
        if n % i == 0:
            factors.append((i, n//i))
    return factors

def main(file_name):
    with open(file_name, 'r') as file:
        for line in file:
            n = int(line)
            factors = factorize(n)
            for factor in factors:
                print(f"{n}={factor[0]}*{factor[1]}")

if __name__ == "__main__":
    main(sys.argv[1])

