#!/usr/bin/python3

import sys
"""
Module to factorise two prime numbers
"""
def factorise():
    """
    A function that factorises a file into two prime numbers
    in the format n = p × q
    """
    try:
        file = sys.argv[1]
        with open(file) as f:
            for line_number in f:
                line_number = int(line_number)
                if line_number % 2 == 0:
                    print("{}={}*{}".format(line_number, line_number // 2, 2))
                    continue
                i = 3
                while i < line_number // 2:
                    if line_number % i == 0:
                        print("{}={}*{}".format(line_number, line_number // i, i))
                        break
                    i + 2
                if i == (line_number // 2) + 1:
                    print("{}={}*{}".format(line_number, line_number, i))
    except IndexError:
        pass
